version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongo.conf:/etc/mongo.conf
    command: ["mongod", "--config", "/etc/mongo.conf"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_URL: "mongodb://127.0.0.1:27017/b2b-marketplace"
      NODE_ENV: production
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  mongo_data:
